referral:
    host: localhost
    user: referral_writer
    password: ProbioWriter
    database: referrals

ipcmLeaderboard:
    host: localhost
    user: referral_writer
    password: ProbioWriter
    database: ipcm_leaderboard

leaderboard:
    host: localhost
    user: referral_writer
    password: ProbioWriter
    database: genomic_board
    
tableName:
    IPCM : ipcm_referral_t
    PROBIO: probio_bloodreferrals
    PSFF: psff_bloodreferrals
    sample_status: sample_status_t
